server:
  port: 8080
spring:
  application: reggie
  datasource:
    druid:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=UTC&characterEncoding=utf-8
      username: root
      password: yxh
      usePinMethod: false
mybatis-plus:
  configLocation:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
reggie:
  path: D:\JavaInformation\瑞吉外卖\image\