server:
  port: 8080
spring:
  application: reggie
  datasource:
    druid:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=UTC&characterEncoding=utf-8
      username: root
      password: yxh
      usePinMethod: false
  redis:
    host: localhost
    port: 6379
    #password: 123456
    database: 0
    jedis:
      #redis连接池配置
      max-active: 8
      max-wait: 1ms
      max-idle: 4
      min-idle: 0
mybatis-plus:
  configLocation:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
reggie:
  path: D:\JavaInformation\瑞吉外卖\image\